version: '3.8'

services:
  python-server:
    build:
      context: ./python-server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./python-server/src:/app/src
    # Adjust the command below if your entry point is different
    # command: ["python", "src/app.py"]

  simple-express-server:
    build:
      context: ./simple-express-server
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./simple-express-server/src:/usr/src/app/src
      - ./simple-express-server/package.json:/usr/src/app/package.json
      - ./simple-express-server/yarn.lock:/usr/src/app/yarn.lock
    command: ["yarn", "start"]
